[package]
name = "kiban_lexer_derive"
description = "Kiban's lexer 🪨"
version = "0.0.1"
edition = "2021"

[dependencies]
proc-macro2 = "1"
syn = "2"
quote = "1"
strum = "0.24"

[lib]
proc-macro = true