[package]
name = "kiban_error"
description = "Kiban's errors ⚠️"
version = "0.0.1"
edition = "2021"

[dependencies]
kiban_commons = { path = "../commons" }
compact_str = "0.7"
miette = "5"
thiserror = "1"